import { ReactNode } from 'react'
import type { Metadata } from 'next'
import '@/styles/globals.css'
import CssBaseline from '@mui/material/CssBaseline'
import type { Theme } from '@mui/material/styles'

import PageLayout from '@/components/common/PageLayout'
import { useRouter } from 'next/router'
import createEmotionCache from '@/utils/createEmotionCache'
import { CacheProvider } from '@emotion/react'
import { ThemeProvider } from '@mui/material'
import PacketThemeProvider from '@/components/theme/PacketThemeProvider'
import { useDarkMode } from '@/hooks/useDarkMode'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config/wagmi'
import AppKitProvider from '@/context/wagmi'
import WalletProvider from '@/components/common/WalletProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Client-side cache, shared for the whole session of the user in the browser.
const clientSideEmotionCache = createEmotionCache()

export const AppProviders = ({ children }: { children: ReactNode | ReactNode[] }) => {
  const isDarkMode = useDarkMode()
  const themeMode = isDarkMode ? 'dark' : 'light'
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <PacketThemeProvider mode={themeMode}>
      <WalletProvider>{children}</WalletProvider>
    </PacketThemeProvider>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <CssBaseline />
          <PageLayout>{children}</PageLayout>
        </AppProviders>
      </body>
    </html>
  )
}
