import { ChainInfo, ChainListResponse } from '@/types/chains'

export const getChainsConfig = async () => ({
  count: 17,
  results: [
    {
      chainId: '1',
      chainName: 'Ethereum',
      description: 'The main Ethereum network',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/1/chain_logo.png',
      l2: false,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/1/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-mainnet.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://etherscan.io/address/{{address}}',
        txHash: 'https://etherscan.io/tx/{{txHash}}',
        api: 'https://api.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'DOMAIN_LOOKUP',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_SWAPS',
        'NATIVE_SWAPS_FEE_ENABLED',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SAP_BANNER',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [
        {
          type: 'oracle',
          uri: 'https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=JNFAU892RF9TJWBU3EV7DJCPIWZY8KEMY1',
          gasParameter: 'FastGasPrice',
          gweiFactor: '1000000000.000000000',
        },
      ],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://cloudflare-eth.com',
      },
      rpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://mainnet.infura.io/v3/',
      },
      safeAppsRpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://mainnet.infura.io/v3/',
      },
      shortName: 'eth',
      theme: {
        textColor: '#001428',
        backgroundColor: '#DDDDDD',
      },
      balancesProvider: {
        chainName: 'ethereum',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '100',
      chainName: 'Gnosis Chain',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/100/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'xDai',
        symbol: 'XDAI',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/100/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-gnosis-chain.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://gnosisscan.io/address/{{address}}',
        txHash: 'https://gnosisscan.io/tx/{{txHash}}/',
        api: 'https://api.gnosisscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_SWAPS',
        'NATIVE_SWAPS_FEE_ENABLED',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'RELAYING',
        'RELAYING_MOBILE',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
        'WEB3AUTH_CREATE_SAFE',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.gnosischain.com/',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.gnosischain.com/',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.gnosischain.com/',
      },
      shortName: 'gno',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#48A9A6',
      },
      balancesProvider: {
        chainName: 'xdai',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '137',
      chainName: 'Polygon',
      description: 'L2 chain (MATIC)',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/137/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Matic',
        symbol: 'MATIC',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/137/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-polygon.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://polygonscan.com/address/{{address}}',
        txHash: 'https://polygonscan.com/tx/{{txHash}}',
        api: 'https://api.polygonscan.com/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trezor',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://polygon-rpc.com',
      },
      rpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://polygon-mainnet.infura.io/v3/',
      },
      safeAppsRpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://polygon-mainnet.infura.io/v3/',
      },
      shortName: 'matic',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#8248E5',
      },
      balancesProvider: {
        chainName: 'polygon',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '1101',
      chainName: 'Polygon zkEVM',
      description: 'Polygon zkEVM',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/1101/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/1101/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-zkevm.safe.global/',
      blockExplorerUriTemplate: {
        address: 'https://zkevm.polygonscan.com/address/{{address}}',
        txHash: 'https://zkevm.polygonscan.com/tx/{{txHash}}',
        api: 'https://api-zkevm.polygonscan.com/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://zkevm-rpc.com',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://zkevm-rpc.com',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://zkevm-rpc.com',
      },
      shortName: 'zkevm',
      theme: {
        textColor: '#000000',
        backgroundColor: '#F5F0FD',
      },
      balancesProvider: {
        chainName: 'polygon-zkevm',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '56',
      chainName: 'BNB Chain',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/56/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'BNB',
        symbol: 'BNB',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/56/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-bsc.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://bscscan.com/address/{{address}}',
        txHash: 'https://bscscan.com/tx/{{txHash}}',
        api: 'https://api.bscscan.com/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://bsc-dataseed.binance.org/',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://bsc-dataseed.binance.org/',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://bsc-dataseed.binance.org/',
      },
      shortName: 'bnb',
      theme: {
        textColor: '#001428',
        backgroundColor: '#F0B90B',
      },
      balancesProvider: {
        chainName: 'binance-smart-chain',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '42161',
      chainName: 'Arbitrum',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/42161/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'AETH',
        symbol: 'AETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/42161/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-arbitrum.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://arbiscan.io/address/{{address}}',
        txHash: 'https://arbiscan.io/tx/{{txHash}}',
        api: 'https://api.arbiscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_SWAPS',
        'NATIVE_SWAPS_FEE_ENABLED',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'RELAY_NATIVE_SWAPS',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://arb1.arbitrum.io/rpc',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://arb1.arbitrum.io/rpc',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://arb1.arbitrum.io/rpc',
      },
      shortName: 'arb1',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#28A0F0',
      },
      balancesProvider: {
        chainName: 'arbitrum',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '10',
      chainName: 'Optimism',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/10/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'OETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/10/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-optimism.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://optimistic.etherscan.io/address/{{address}}',
        txHash: 'https://optimistic.etherscan.io/tx/{{txHash}}',
        api: 'https://api-optimistic.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.optimism.io/',
      },
      rpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://optimism-mainnet.infura.io/v3/',
      },
      safeAppsRpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://optimism-mainnet.infura.io/v3/',
      },
      shortName: 'oeth',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#F01A37',
      },
      balancesProvider: {
        chainName: 'optimism',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '8453',
      chainName: 'Base',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/8453/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/8453/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-base.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://basescan.org/address/{{address}}',
        txHash: 'https://basescan.org/tx/{{txHash}}',
        api: 'https://basescan.org/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://developer-access-mainnet.base.org',
      },
      rpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://base-mainnet.infura.io/v3/',
      },
      safeAppsRpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://base-mainnet.infura.io/v3/',
      },
      shortName: 'base',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#0052FF',
      },
      balancesProvider: {
        chainName: 'base',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '59144',
      chainName: 'Linea',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/59144/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/59144/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-linea.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://lineascan.build/address/{{address}}',
        txHash: 'https://lineascan.build/tx/{{txHash}}',
        api: 'https://api.lineascan.build/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SPEED_UP_TX',
        'TX_SIMULATION',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.linea.build',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.linea.build',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.linea.build',
      },
      shortName: 'linea',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#121212',
      },
      balancesProvider: {
        chainName: 'linea',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '324',
      chainName: 'zkSync Era',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/324/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/324/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-zksync.safe.global/',
      blockExplorerUriTemplate: {
        address: 'https://explorer.zksync.io/address/{{address}}',
        txHash: 'https://explorer.zksync.io/tx/{{txHash}}',
        api: 'https://api.explorer.zksync.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SPEED_UP_TX',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.era.zksync.io',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.era.zksync.io',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.era.zksync.io',
      },
      shortName: 'zksync',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#000000',
      },
      balancesProvider: {
        chainName: 'zksync-era',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '534352',
      chainName: 'Scroll',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/534352/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/534352/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-scroll.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://scrollscan.com/address/{{address}}',
        txHash: 'https://scrollscan.com/tx/{{txHash}}',
        api: 'https://scrollscan.com/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://lb.drpc.org/ogrpc?network=scroll&dkey=AokOi_Qn4kLNq-alvNoIrf_JcGZ4NIoR76RchkHL9tz4',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://lb.drpc.org/ogrpc?network=scroll&dkey=AokOi_Qn4kLNq-alvNoIrf_JcGZ4NIoR76RchkHL9tz4',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://lb.drpc.org/ogrpc?network=scroll&dkey=AokOi_Qn4kLNq-alvNoIrf_JcGZ4NIoR76RchkHL9tz4',
      },
      shortName: 'scr',
      theme: {
        textColor: '#000000',
        backgroundColor: '#FFEEDA',
      },
      balancesProvider: {
        chainName: 'scroll',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '196',
      chainName: 'X Layer',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/196/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'OKB',
        symbol: 'OKB',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/196/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-xlayer.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://www.oklink.com/xlayer/address/{{address}}',
        txHash: 'https://www.oklink.com/xlayer/tx/{{txHash}}',
        api: 'https://not-applicable.com',
      },
      disabledWallets: [
        'coinbase',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SPEED_UP_TX',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.xlayer.tech',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.xlayer.tech',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.xlayer.tech',
      },
      shortName: 'xlayer',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#000000',
      },
      balancesProvider: {
        chainName: null,
        enabled: false,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '42220',
      chainName: 'Celo',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/42220/chain_logo.png',
      l2: false,
      isTestnet: false,
      nativeCurrency: {
        name: 'CELO',
        symbol: 'CELO',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/42220/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-celo.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://explorer.celo.org/mainnet/address/{{address}}',
        txHash: 'https://explorer.celo.org/mainnet/tx/{{txHash}}',
        api: 'https://explorer.celo.org/mainnet/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.ankr.com/celo',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.ankr.com/celo',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.ankr.com/celo',
      },
      shortName: 'celo',
      theme: {
        textColor: '#000000',
        backgroundColor: '#FCFF52',
      },
      balancesProvider: {
        chainName: 'celo',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '43114',
      chainName: 'Avalanche',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/43114/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Avalanche',
        symbol: 'AVAX',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/43114/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-avalanche.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://snowtrace.io/address/{{address}}',
        txHash: 'https://snowtrace.io/tx/{{txHash}}',
        api: 'https://api.snowtrace.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'MOONPAY_MOBILE',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RISK_MITIGATION',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://api.avax.network/ext/bc/C/rpc',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://api.avax.network/ext/bc/C/rpc',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://api.avax.network/ext/bc/C/rpc',
      },
      shortName: 'avax',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#000000',
      },
      balancesProvider: {
        chainName: 'avalanche',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '1313161554',
      chainName: 'Aurora',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/1313161554/chain_logo.png',
      l2: true,
      isTestnet: false,
      nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/1313161554/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-aurora.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://aurorascan.dev/address/{{address}}/transactions',
        txHash: 'https://aurorascan.dev/tx/{{txHash}}/',
        api: 'https://aurorascan.dev/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'pk',
        'safeMobile',
        'socialSigner',
        'tally',
        'trezor',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'EIP1271',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.aurora.dev',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.aurora.dev',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://mainnet.aurora.dev',
      },
      shortName: 'aurora',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#78D64B',
      },
      balancesProvider: {
        chainName: 'aurora',
        enabled: true,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '11155111',
      chainName: 'Sepolia',
      description: 'Ethereum Testnet Sepolia',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/11155111/chain_logo.png',
      l2: true,
      isTestnet: true,
      nativeCurrency: {
        name: 'Sepolia Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/11155111/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-sepolia.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://sepolia.etherscan.io/address/{{address}}',
        txHash: 'https://sepolia.etherscan.io/tx/{{txHash}}',
        api: 'https://api-sepolia.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'NONE',
        'opera',
        'operaTouch',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: '0x8FADE66B79cC9f707aB26799354482EB93a5B7dD',
      features: [
        'COUNTERFACTUAL',
        'DEFAULT_TOKENLIST',
        'DELETE_TX',
        'DOMAIN_LOOKUP',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_SWAPS',
        'NATIVE_SWAPS_FEE_ENABLED',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'RECOVERY',
        'SAFE_141',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'SPENDING_LIMIT',
        'TX_SIMULATION',
        'ZODIAC_ROLES',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://rpc.sepolia.org',
      },
      rpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://sepolia.infura.io/v3/',
      },
      safeAppsRpcUri: {
        authentication: 'API_KEY_PATH',
        value: 'https://sepolia.infura.io/v3/',
      },
      shortName: 'sep',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#B8AAD5',
      },
      balancesProvider: {
        chainName: null,
        enabled: false,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
    {
      chainId: '84532',
      chainName: 'Base Sepolia',
      description: '',
      chainLogoUri: 'https://safe-transaction-assets.safe.global/chains/84532/chain_logo.png',
      l2: true,
      isTestnet: true,
      nativeCurrency: {
        name: 'Base Sepolia Ether',
        symbol: 'ETH',
        decimals: 18,
        logoUri: 'https://safe-transaction-assets.safe.global/chains/84532/currency_logo.png',
      },
      transactionService: 'https://safe-transaction-base-sepolia.safe.global',
      blockExplorerUriTemplate: {
        address: 'https://sepolia.basescan.org/address/{{address}}',
        txHash: 'https://sepolia.basescan.org/tx/{{txHash}}',
        api: 'https://api-sepolia.basescan.org/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}',
      },
      disabledWallets: [
        'coinbase',
        'keystone',
        'NONE',
        'opera',
        'operaTouch',
        'safeMobile',
        'socialSigner',
        'tally',
        'trust',
        'walletConnect',
      ],
      ensRegistryAddress: null,
      features: [
        'COUNTERFACTUAL',
        'DELETE_TX',
        'EIP1271',
        'EIP1559',
        'ERC721',
        'NATIVE_WALLETCONNECT',
        'PUSH_NOTIFICATIONS',
        'SAFE_APPS',
        'SAFE_TX_GAS_OPTIONAL',
        'SPEED_UP_TX',
        'TX_SIMULATION',
      ],
      gasPrice: [],
      publicRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://sepolia.base.org',
      },
      rpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://sepolia.base.org',
      },
      safeAppsRpcUri: {
        authentication: 'NO_AUTHENTICATION',
        value: 'https://sepolia.base.org',
      },
      shortName: 'basesep',
      theme: {
        textColor: '#ffffff',
        backgroundColor: '#0000FF',
      },
      balancesProvider: {
        chainName: null,
        enabled: false,
      },
      contractAddresses: {
        safeSingletonAddress: null,
        safeProxyFactoryAddress: null,
        multiSendAddress: null,
        multiSendCallOnlyAddress: null,
        fallbackHandlerAddress: null,
        signMessageLibAddress: null,
        createCallAddress: null,
        simulateTxAccessorAddress: null,
        safeWebAuthnSignerFactoryAddress: null,
      },
    },
  ],
})
